### ISSUE TITLE
您好，C语言中关于if语句后输入大括号的问题

### ISSUE THREAD

**Issue by DOWhy** [pein0119/emacs.d#2]
c语言中if语句输入大括号是这样的：
if(...)
    {
      ...
    }
能麻烦您教教我怎么输入大括号后自动变为下面这样吗：
if(...)
{
}

谢谢，我刚刚开始学用emacs，现在实在是不会改。

**Comment by pein0119** [comment]
(setq c-default-style "linux"
          c-basic-offset 4)

在你的配置文件里加上这个试试

**Comment by DOWhy** [comment]
谢谢。
